/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedPicksRouteImport } from './routes/_authenticated/picks'
import { Route as AuthenticatedSurvivorRouteImport } from './routes/_authenticated/survivor'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedLeaguesIndexRouteImport } from './routes/_authenticated/leagues.index'
import { Route as AuthenticatedManagerUserIdRouteImport } from './routes/_authenticated/manager.$userId'
import { Route as ApiPublicNflSyncRouteImport } from './routes/api/public/nfl-sync'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPicksRoute = AuthenticatedPicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSurvivorRoute = AuthenticatedSurvivorRouteImport.update({
  id: '/survivor',
  path: '/survivor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaguesIndexRoute =
  AuthenticatedLeaguesIndexRouteImport.update({
    id: '/leagues/',
    path: '/leagues/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerUserIdRoute =
  AuthenticatedManagerUserIdRouteImport.update({
    id: '/manager/$userId',
    path: '/manager/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNflSyncRoute = ApiPublicNflSyncRouteImport.update({
  id: '/api/public/nfl-sync',
  path: '/api/public/nfl-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/chat': typeof AuthenticatedChatRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/picks': typeof AuthenticatedPicksRoute
  '/survivor': typeof AuthenticatedSurvivorRoute
  '/team': typeof AuthenticatedTeamRoute
  '/manager/$userId': typeof AuthenticatedManagerUserIdRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/leagues/': typeof AuthenticatedLeaguesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/chat': typeof AuthenticatedChatRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/picks': typeof AuthenticatedPicksRoute
  '/survivor': typeof AuthenticatedSurvivorRoute
  '/team': typeof AuthenticatedTeamRoute
  '/manager/$userId': typeof AuthenticatedManagerUserIdRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/leagues': typeof AuthenticatedLeaguesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/picks': typeof AuthenticatedPicksRoute
  '/_authenticated/survivor': typeof AuthenticatedSurvivorRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/manager/$userId': typeof AuthenticatedManagerUserIdRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/_authenticated/leagues/': typeof AuthenticatedLeaguesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/chat'
    | '/leaderboard'
    | '/picks'
    | '/survivor'
    | '/team'
    | '/manager/$userId'
    | '/api/public/nfl-sync'
    | '/leagues/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/chat'
    | '/leaderboard'
    | '/picks'
    | '/survivor'
    | '/team'
    | '/manager/$userId'
    | '/api/public/nfl-sync'
    | '/leagues'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join'
    | '/_authenticated/chat'
    | '/_authenticated/leaderboard'
    | '/_authenticated/picks'
    | '/_authenticated/survivor'
    | '/_authenticated/team'
    | '/_authenticated/manager/$userId'
    | '/api/public/nfl-sync'
    | '/_authenticated/leagues/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  ApiPublicNflSyncRoute: typeof ApiPublicNflSyncRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/picks': {
      id: '/_authenticated/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof AuthenticatedPicksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/survivor': {
      id: '/_authenticated/survivor'
      path: '/survivor'
      fullPath: '/survivor'
      preLoaderRoute: typeof AuthenticatedSurvivorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leagues/': {
      id: '/_authenticated/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof AuthenticatedLeaguesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/$userId': {
      id: '/_authenticated/manager/$userId'
      path: '/manager/$userId'
      fullPath: '/manager/$userId'
      preLoaderRoute: typeof AuthenticatedManagerUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/nfl-sync': {
      id: '/api/public/nfl-sync'
      path: '/api/public/nfl-sync'
      fullPath: '/api/public/nfl-sync'
      preLoaderRoute: typeof ApiPublicNflSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPicksRoute: typeof AuthenticatedPicksRoute
  AuthenticatedSurvivorRoute: typeof AuthenticatedSurvivorRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedManagerUserIdRoute: typeof AuthenticatedManagerUserIdRoute
  AuthenticatedLeaguesIndexRoute: typeof AuthenticatedLeaguesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPicksRoute: AuthenticatedPicksRoute,
  AuthenticatedSurvivorRoute: AuthenticatedSurvivorRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedManagerUserIdRoute: AuthenticatedManagerUserIdRoute,
  AuthenticatedLeaguesIndexRoute: AuthenticatedLeaguesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  ApiPublicNflSyncRoute: ApiPublicNflSyncRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
